title = "MAC Miner"

# use toml to go to get code
# https://xuri.me/toml-to-go/
[server]
IP = "39.99.160.245"
port = 1883
connection_max = 50

[client]
username = "userA"
passwd = "userfast"
subtopic="mtopic"
pubtopic="mtopic"
store=":memory:"
ID="testID"
msgRepeatNum=2
TimeIntervel=10

[mysql]
ip= "39.99.160.245"
port= 3306
name = "fastroot"
passwd= "test123456"
