name: Build CI For golang

on:
  push:
#  schedule:
#    - cron: 0 0 1 * *
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set GOPATH
        run: |
             echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
             echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
             echo "##[set-env name=TAG_NAME;]$(date +%Y%m%d)"
             echo "##[set-env name=NAME;]$(date +%Y%m%d)"
             echo "::set-env name=MAC_TESTTIMES::20"
        shell: bash
      - name: Test
        run:
          ./runMqtt.sh


